version: '3'
services:
    nginx:
        image: tutum/nginx
        ports:
            - "80:80"
        links:
            - phpfpm
        volumes:
            - ./nginx/default:/etc/nginx/sites-available/default
            - ./nginx/default:/etc/nginx/sites-enabled/default
    
            - ./nginx/nginx-error.log:/var/log/nginx/error.log
            - ./nginx/nginx-access.log:/var/log/nginx/access.log
    phpfpm:
        build:
            context: ./
            dockerfile: phpfpm-config
        ports:
            - "9000:9000"
        volumes:
            - ./laravel:/usr/share/nginx/html
    mysql:
      image: mariadb
      volumes:
         - ./dump.sql:/home/dump.sql
      environment:
        MYSQL_ROOT_PASSWORD: admin
      ports:
        - "3306:3306"
